deps(gymnasium): update gymnasium version to 0.28.1
OmniSafeAI/safety-gymnasium pull request #41
Opened 2023-04-13 07:49 UTC by muchvo

## Description

1. Update gymnasium version to 0.28.1

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213

- [x] I have raised an issue to propose this change ([required](https://github.com/OmniSafeAI/safety-gymnasium/issues) for new features and bug fixes) #39 

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Implemented Tasks

- [ ] Subtask 1
- [ ] Subtask 2
- [ ] Subtask 3

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/OmniSafeAI/safety-gymnasium/blob/main/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format`. (**required**)
- [x] I have checked the code using `make lint`. (**required**)
- [x] I have ensured `make test` pass. (**required**)

2023-04-13 15:40 UTC, zmsn-2077 submitted a review, later dismissed
LGTM.

2023-04-13 15:51 UTC, muchvo commented
> It's time to bump the version to 0.3.0 after the PR #16 finishes.

got it

2023-04-14 16:11 UTC, Gaiejj requested changes

2023-04-14 16:11 UTC, Gaiejj commented on README.md
> +  apt-get install python3-opengl
Please note that this method is not work on headless server

2023-04-14 16:36 UTC, Gaiejj approved these changes
LGTM.

2023-04-14 17:07 UTC, zmsn-2077 approved these changes

2023-04-15 00:30 UTC, merged